on join:
  set player's tab list header to "&f%nl%<##72DE15>&LG<##75E220>&LR<##78E52C>&LA<##7BE937>&LN<##7EED43>&LD<##80F04E>&LH<##83F45A>&LA<##86F865>&LV<##89FB71>&LE<##8CFF7C>&LN%nl%&8%smallcaps("season one")%%nl%&f"
  set player's tab list footer to "&f%nl%&2%smallcaps("MMORPG")% &8* &f%placeholder "player_ping" from player%ms &8* &a%smallcaps("Grandhaven.minehut.net")% %nl%&a%placeholder "server_online"% &f%smallcaps("global")%%nl%"

function smallcaps(text: text) :: text:
	loop split "ᴀ,a|ʙ,b|ᴄ,c|ᴅ,d|ᴇ,e|ꜰ,f|ɢ,g|ʜ,h|ɪ,i|ǫ,q|ᴊ,j|ᴋ,k|ʟ,l|ᴍ,m|ɴ,n|ᴏ,o|ᴘ,p|Q,q|ʀ,r|ꜱ,s|ᴛ,t|ᴜ,u|ᴠ,v|ᴡ,w|x,x|ʏ,y|ᴢ,z" at "|":
		set {_a::*} to split loop-value at ","
		replace all {_a::2} with {_a::1} in {_text}
	return {_text}
